version: 2

project_name: azemu

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/azemu
    binary: azemu
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
      - "ghcr.io/zerodeth/azemu:{{ .Version }}"
      - "ghcr.io/zerodeth/azemu:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/ZeroDeth/azemu"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github-native

release:
  github:
    owner: ZeroDeth
    name: azemu
  prerelease: auto
